channels:
  - conda-forge
dependencies:
  - appmode
  - gensim
  - matplotlib
  - pandas
  - setuptools
  - numpy
  - ipywidgets
  - wordcloud
  - pandas
  - nltk
  - ipython
  - pyLDAvis
  - scikit_learn
  - vaderSentiment
  - xlrd
